In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt



df = pd.read_csv("data/dataset-merged-2.csv")


display(df)

,Datum,Monat,Tag,Restaurant,Terrasse,is_fr_sa,Ferien-Value,Special-Day-Value,Niederschlag Tagessumme 6 UTC,Sonnenscheindauer Tagessumme,Lufttemperatur 2m Tagesmittel,Durchschnittliche Anzahl Geburtstage (über 100 Jahre),Tagesumsatz Restaurant
0,2021-01-01,Januar,Fr,1620.2,0.0,1,1.0,1.0,0.6,0.0,1.7,6852.12,1620.2
1,2021-01-02,Januar,Sa,872.9,0.0,1,1.0,0.0,0.0,0.0,1.5,6852.12,872.9
2,2021-01-03,Januar,So,0.0,0.0,0,1.0,0.0,0.0,0.0,0.5,6852.12,0.0
3,2021-01-04,Januar,Mo,636.2,0.0,0,1.0,0.0,0.0,0.0,0.1,6852.12,636.2
4,2021-01-05,Januar,Di,694.5,0.0,0,1.0,0.0,0.0,0.0,-0.2,6852.12,694.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1722,2025-11-12,November,Mi,6279.9,362.6,0,0.0,0.0,0.0,419.0,6.2,6225.59,6642.5
1723,2025-11-13,November,Do,6735.1,307.4,0,0.0,0.0,0.0,426.0,8.1,6225.59,7042.5
1724,2025-11-14,November,Fr,12458.5,80.0,1,0.0,0.0,0.0,113.0,9.2,6225.59,12538.5
1725,2025-11-15,November,Sa,15362.0,1909.4,1,0.0,0.0,0.0,396.0,12.0,6225.59,17271.4
1726,2025-11-16,November,So,11721.3,0.0,0,0.0,0.0,0.4,0.0,8.8,6225.59,11721.3

In [5]:
start = "2021-01-01"
end   = "2025-11-16"
full_range = pd.date_range(start=start, end=end, freq="D")

# Convert DataFrame dates to a DatetimeIndex
df_dates = pd.to_datetime(df['Datum'])

# Identify missing dates
missing_dates = full_range.difference(df_dates)

# Create new DataFrame of missing dates
missing_df = pd.DataFrame({'missing_date': missing_dates})

display(missing_df)

   missing_date
0    2022-05-31
1    2022-09-30
2    2024-02-27
3    2024-02-28
4    2024-02-29
5    2024-05-29
6    2024-05-30
7    2024-05-31
8    2024-06-28
9    2024-06-29
10   2024-06-30
11   2024-07-30
12   2024-07-31
13   2024-08-29
14   2024-08-30
15   2024-08-31
16   2024-09-30
17   2024-10-29
18   2024-10-30
19   2024-10-31
20   2024-11-28
21   2024-11-29
22   2024-11-30
23   2025-01-28
24   2025-01-29
25   2025-01-30
26   2025-01-31
27   2025-02-25
28   2025-02-26
29   2025-02-27
30   2025-02-28
31   2025-04-29
32   2025-04-30
33   2025-05-28
34   2025-05-29
35   2025-05-30
36   2025-05-31
37   2025-06-27
38   2025-06-28
39   2025-06-29
40   2025-06-30
41   2025-07-29
42   2025-07-30
43   2025-07-31
44   2025-08-28
45   2025-08-29
46   2025-08-30
47   2025-08-31
48   2025-09-29
49   2025-09-30
50   2025-10-28
51   2025-10-29
52   2025-10-30
53   2025-10-31